### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by tmcw** [mapnik/mapnik.github.com#10]
* https://gist.github.com/tmcw/ae916f722b57fb304a29

So we have

* [x] Python
* [x] Node
* [x] C++

/cc @flippmoke for the c++ example, plz gist here and @amyleew will integrate into the site

**Comment by amyleew** [comment]
add from @flippmoke via chat: https://gist.github.com/amyleew/dac38b55861a43075f78

cc @tmcw
