### ISSUE TITLE
API links

### ISSUE THREAD

**Issue by tmcw** [mapnik/mapnik.github.com#11]
* [x] Node: http://mapnik.org/node-mapnik/documentation/
* [ ] Python: can we update http://mapnik.org/docs/v2.2.0/api/python/index.html ?
* [ ] C++: none

**Comment by springmeyer** [comment]
python currently gets regenerated like https://github.com/mapnik/mapnik/wiki/MapnikReleaseSteps#tagging. We can do a whole lot better (doc style and generation method), but that would be the minimum thing to do.

**Comment by springmeyer** [comment]
I think we should focus on node and python docs, get them right, and only after worry about C++ docs. So, therefore C++ docs are not actionable, don't need a ticket at this point. Let's track next actions on python and node in new tickets. New one for python at https://github.com/mapnik/mapnik.github.com/issues/24
