### ISSUE TITLE
Recessive text ?

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik.github.com#14]
@amyleew 

![above-else](https://cloud.githubusercontent.com/assets/59056/8087279/d2052f58-0f91-11e5-97d2-99c3f39b48d6.png)

The above is too recessive at least on my retina display. 

```
stacks built with mapnik
OpenStreetMap | Mapbox | CartoDB | Stamen | MapQuest | Kosmtik
```
This is stuff we want people to notice ! :) 
/cc @springmeyer @flippmoke

**Comment by amyleew** [comment]
@artemp updated and linked to urls + repo for kosmtik

![image](https://cloud.githubusercontent.com/assets/4587826/8091655/1839c2b8-0f83-11e5-8aee-addafcad15d7.png)

/cc @flippmoke @springmeyer

**Comment by artemp** [comment]
@amyleew - looks more prominent, thanks!
