### ISSUE TITLE
Mobile browsers

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik.github.com#15]
![img_0144](https://cloud.githubusercontent.com/assets/59056/8087545/815df6b4-0f93-11e5-9b1d-438432f6cf7f.PNG)

New design works well overall on mobile but we need to adjust margins a little bit  ^

**Comment by amyleew** [comment]
margin perfection @artemp 

![image](https://cloud.githubusercontent.com/assets/4587826/8092770/310cbcbc-0f8a-11e5-9c35-e4d2eeff5788.png)
