### ISSUE TITLE
Bulleted lists not formatting properly

### ISSUE THREAD

**Issue by amyleew** [mapnik/mapnik.github.com#23]
Not with:

 - format1
 - format2

Nor with: 

* one
* two

or:

1. this
2. that

/cc @flippmoke @springmeyer

**Comment by springmeyer** [comment]
I notice that `-` or `*` work correctly to generate `<ul><li>...`. The problem is that https://github.com/mapnik/mapnik.github.com/blob/news-redesign-post/css/mapnik.css#L697 is hiding the bullets. It looks like we also need some more padding around list elements.

**Comment by amyleew** [comment]
@springmeyer I'll hit that in the css

**Comment by amyleew** [comment]
@springmeyer - Fixed but bothered by rendering on splash page... content is cutting off a hard return, but there is room for the bulleted list.

![image](https://cloud.githubusercontent.com/assets/4587826/8114221/f34cfe98-1040-11e5-94db-e86f00fded60.png)

**Comment by flippmoke** [comment]
@amyleew lets just worry about that later and roll out :+1:

**Comment by amyleew** [comment]
:+1: @flippmoke
