### ISSUE TITLE
Resize mapdesign.png

### ISSUE THREAD

**Issue by tmcw** [mapnik/mapnik.github.com#29]
http://mapnik.org/images/mapdesign.png is 3.5MB - this burns bad mostly because the super slow Milwaukee wifi I'm using is slow, but that's still quite a large image that could probably be smaller jpeg'ed.

**Comment by amyleew** [comment]
@tmcw - Got it down to 1.3MB as PNG... How's that? Only image on the page, so it needs to be excellent and PNG is best. Thoughts?

**Comment by tmcw** [comment]
:+1: great

**Comment by amyleew** [comment]
merged!
