### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by bigmadhabib** [mapnik/mapnik.github.com#34]
Hi all,

Since the new site redesign, the downloads section (http://mapnik.org/download/) does not exist anymore.  Is there a location where Mapnik Windows binaries can be found?

Thanks!

**Comment by BergWerkGIS** [comment]
[Windows 32 bit Package](http://mapnik.s3.amazonaws.com/dist/v2.2.0/mapnik-win-v2.2.0.zip)
[Windows 32 bit SDK](http://mapnik.s3.amazonaws.com/dist/v2.2.0/mapnik-win-sdk-v2.2.0.zip)
[Setup instructions](https://gist.github.com/springmeyer/5651701)

**Comment by artemp** [comment]
@bigmadhabib - thanks for pointing out - we need to add download section back
/cc @springmeyer @flippmoke

**Comment by bigmadhabib** [comment]
Thanks!

**Comment by amyleew** [comment]
@flippmoke @springmeyer - can downloads page link from the footer? 
![image](https://cloud.githubusercontent.com/assets/4587826/8219036/287f3e40-1515-11e5-8b0f-c2a4f04034d9.png)

Or does it need more prominent location? 

/cc @artemp

**Comment by amyleew** [comment]
thanks @BergWerkGIS @bigmadhabib - added to new site!

/cc @artemp @flippmoke @springmeyer
