### ISSUE TITLE
Update downloads page for Mapnik 3.0.0

### ISSUE THREAD

**Issue by flippmoke** [mapnik/mapnik.github.com#38]
Put the new source distribution files for Mapnik 3.0.0 under the downloads section on mapnik.org

**Comment by flippmoke** [comment]
![image](https://cloud.githubusercontent.com/assets/1794907/8443118/aaed372c-1f49-11e5-9ccb-cc1156a963be.png)

Shifting layout some, know that we do not have all the binaries yet will address that as soon as we get them @springmeyer

**Comment by springmeyer** [comment]
tracking at https://github.com/mapnik/mapnik.github.com/pull/40
