### ISSUE TITLE
Example XML on index page

### ISSUE THREAD

**Issue by speg** [mapnik/mapnik.github.com#48]
I was trying to use the sample code on the homepage and kept getting this error:

```
Error: Could not create datasource. Required parameter 'type' is missing  encountered during parsing of layer 'world' in Layer of './style.xml'
```

I fixed it by adding this line to the XML file:
```xml
            <Parameter name="type">shape</Parameter>
```
This and adding a link to download the shape files would help people get started without having to debug.

**Comment by mapsam** [comment]
Good eye @speg! I will add `<Parameter name="type">shape</Parameter>` to the example XML on mapnik.org.

I wonder if using `ne_110m_countries.shp` is too specific? Including a link to that natural earth data download would be out of scope for the mapnik.org homepage. Maybe making the example more general and updating to `<Parameter name="file">path/to/your/shapefile.shp</Parameter>` would make most sense.

**Comment by speg** [comment]
@mapsam Great! I am pretty green when it comes to mapping and don't even really know what a shape file is, so I think including some type of demo data is good. I happened to realize that `ne_110m_countries.shp` was the same file as used in the tutorial, but that isn't necessarily obvious if you've just landed on the home page.

**Comment by mapsam** [comment]
Thanks again for the :eyes: @speg :+1: 

More documentation on file types will be helpful, but will consider that a peripheral issue. Cheers!
