### ISSUE TITLE
mapnik.org - broken after github upgrade to Jekyll 3  

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik.github.com#50]
/cc @springmeyer @amyleew

**Comment by artemp** [comment]
### GitHub Pages was recently upgraded to Jekyll 3.0.

Today I posted new blog entry re: mapnik 3.0.10 release. After that I received a few emails like this one bellow
```
The page build completed successfully, but returned the following warning:

You are currently using the 'rdiscount' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

and mapnik.org stopped working  e.g  site can't be build correctly  (see mapnik.org - missing news entries)

I don't know for sure but It seems like 'nokogiri' is a bad guy (I'm had a real trouble installing it on OS X 10.11 and eventually gave up). In any case this needs some action. I strongly suspect 'nokogiri' is behind currently broken mapnik.org and all other world problems. 

Sooo... can we remove 'nokogiri' dependency and replace it with something behaving better ? Does anyone experienced the same issues ? Thanks in advance!

/cc @amyleew @springmeyer @tmcw @jfirebaugh @tristen

**Comment by artemp** [comment]
#### Update
I can now replicate locally but no idea what's causing this issue, yet.

I managed to compile `nokogiri` from source after installing latest ruby (also source compile)
```
sudo gem install nokogiri  -- --use-system-libraries --with-xml2-include=/usr/local/include/libxml2 --with-xml2-lib=/usr/local/lib
```
I can run 'jekyll build` + `jekyll serve --watch` no errors or warnings but the site is still missing news TOC.

**Comment by artemp** [comment]
#### Latest 

I think figured out how this things works and I'll push a fix shortly..

**Comment by amyleew** [comment]
@artemp - I was in the process of updating my ruby version to test this locally. What was the issue here?

**Comment by artemp** [comment]
@amyleew - nm I fixed all issues. I had to do 06fdc9c9567e581033c220abcf014c5f55a58ada in order to have `correct` (?) layout on retina display > 1200px resolution. Can you take a look if this is a right way to do it ?

**Comment by amyleew** [comment]
@artemp - layout update looks good!

**Comment by springmeyer** [comment]
Closing as this appears to be resolved from the above comments.
