### ISSUE TITLE
Atom-Feed XML Parsing Error

### ISSUE THREAD

**Issue by w1n5l0w** [mapnik/mapnik.github.com#58]
I'll get this XML paring error when trying to fetch the mapnik.org/atom.xml feed:

    XML Parsing Error: not well-formed
    Location: https://mapnik.org/atom.xml
    Line Number 16, Column 69:
    <link href='https://fonts.googleapis.com/css?family=Maven+Pro&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    --------------------------------------------------------------------^

**Comment by artemp** [comment]
Fixed in de4048ca9f346aba97ad38a6c330703e1c67c96d
