### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by tmcw** [mapnik/mapnik.github.com#7]
@amyleew is grabbing this, I'm helping out with copy and API so that it can land sooner rather than later.

* [x] Front page copy first draft
* [x] First API documentation first draft
* [x] http://mapnik.org/news/ integration
* [x] http://mapnik.org/faq/
* [x] http://mapnik.org/licence/
* [x] Front page copy final draft

**Comment by amyleew** [comment]
also tracking here https://github.com/mapbox/mapnik-internal/issues/16

**Comment by springmeyer** [comment]
\o/ - we are wrapping up over at https://github.com/mapnik/mapnik.github.com/pull/12 and planning to got live today.
